// Terratest e2e for the OVH twin of S18 — apply → assert → destroy against real
// OVH Object Storage. The base lab hardcoded `test`/`test` LocalStack creds and
// asserted an exact fixed bucket name; this twin reads S3 credentials from the
// environment and asserts the naming-module pattern (the suffix is random and
// OVH names are globally unique).
//
//	export AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... AWS_DEFAULT_REGION=gra
//	go test ./...   # or via the pinned container lane
package test

import (
	"os"
	"strings"
	"testing"

	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/require"
)

func TestOVHS3Bucket(t *testing.T) {
	region := os.Getenv("AWS_DEFAULT_REGION")
	if region == "" {
		region = "gra"
	}

	opts := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
		TerraformBinary: "tofu",
		TerraformDir:    ".",
		NoColor:         true,
		Vars: map[string]interface{}{
			"project":      "crmapp",
			"cloud_region": region,
		},
		EnvVars: map[string]string{
			// Real OVH S3 credentials from the environment — never hardcoded.
			"AWS_ACCESS_KEY_ID":     os.Getenv("AWS_ACCESS_KEY_ID"),
			"AWS_SECRET_ACCESS_KEY": os.Getenv("AWS_SECRET_ACCESS_KEY"),
			"AWS_DEFAULT_REGION":     region,
		},
	})

	defer terraform.Destroy(t, opts)

	terraform.InitAndApply(t, opts)

	bucket := terraform.Output(t, opts, "bucket_name")
	require.True(t, strings.HasPrefix(bucket, "s3-crmapp-"),
		"expected bucket name to start with s3-crmapp-, got %q", bucket)
	// The suffix is generated by modules/naming, so assert the pattern, not a
	// fixed name (C1: OVH bucket names are globally unique).
	require.Regexp(t, `^s3-crmapp-d-web-[a-f0-9]{4}$`, bucket)
}
