import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { describe, it } from 'node:test'

import {
  canonicalDayTotals,
  findGeneratedDrift,
  renderDeck,
  sections as workshopSections,
  validateDeckTierTruth,
  validateManifest,
  validatePlanningLanguage,
  validateRunbookTimings,
  validateSectionFrontmatter,
  validateSyllabusCatalog,
  validateSyllabusTimings,
} from './deck-manifest.mjs'

const section = (id, overrides = {}) => ({
  id,
  slug: `topic-${id.toLowerCase()}`,
  title: `Topic ${id}`,
  tier: 'core',
  day: 1,
  canonical: true,
  status: 'authored',
  slidesMinutes: 10,
  labMinutes: 10,
  ...overrides,
})

describe('deck manifest validation', () => {
  it('rejects a manifest whose source section is missing', () => {
    const root = mkdtempSync(join(tmpdir(), 'ot-deck-'))
    assert.throws(
      () => validateManifest([section('S00')], { repoRoot: root }),
      /missing section source.*S00/i,
    )
  })

  it('reports generated deck drift instead of silently overwriting it', () => {
    const root = mkdtempSync(join(tmpdir(), 'ot-deck-'))
    writeFileSync(join(root, 'slides-day-1.md'), 'stale\n')

    assert.deepEqual(
      findGeneratedDrift(new Map([
        ['slides-day-1.md', 'fresh\n'],
        ['slides-day-2.md', 'new\n'],
      ]), { repoRoot: root }),
      ['slides-day-1.md', 'slides-day-2.md'],
    )
  })

  it('rejects contradictory section day and tier frontmatter', () => {
    assert.throws(
      () => validateSectionFrontmatter(
        section('S03', { day: 1, tier: 'core' }),
        `---\nday: Day 2\nsection: '03'\ntier: optional\n---\n`,
      ),
      /S03.*day.*tier/i,
    )
  })

  it('rejects syllabus catalog drift from the manifest', () => {
    const manifest = [section('S11', { tier: 'optional', day: 1 })]
    const catalog = `
| ID | Section | Tier | Day | Status | 3-day cut |
| --- | --- | --- | --- | --- | --- |
| S11 | TACO landscape | core | 1 | authored | Skip |
`
    assert.throws(
      () => validateSyllabusCatalog(manifest, catalog),
      /S11.*tier.*optional/i,
    )
  })

  it('rejects per-section timing drift from the manifest', () => {
    const manifest = [section('S12', { day: 2, slidesMinutes: 20, labMinutes: 20 })]
    const timings = `
| ID | Section | Slides | Lab |
| --- | --- | ---: | ---: |
| S12 | Testing pyramid | 21 | 20 |
`
    assert.throws(
      () => validateSyllabusTimings(manifest, timings),
      /S12.*slides.*20/i,
    )
  })

  it('derives canonical totals and rejects planning drift', () => {
    const manifest = [
      section('S00', { canonical: true, day: 1, slidesMinutes: 40, labMinutes: 20 }),
      section('S01', { canonical: true, day: 1, slidesMinutes: 40, labMinutes: 20 }),
    ]
    assert.deepEqual(canonicalDayTotals(manifest).get(1), {
      slides: 80,
      lab: 40,
      total: 120,
    })
    assert.doesNotThrow(
      () => validatePlanningLanguage('Day 1: 120 minutes planned.', manifest),
    )
    assert.throws(
      () => validatePlanningLanguage('Day 1: 121 minutes planned.', manifest),
      /Day 1.*121.*expected.*120/i,
    )
  })

  it('validates deck tier truth with verify.sh-compatible errors', () => {
    const root = mkdtempSync(join(tmpdir(), 'ot-deck-'))
    writeFileSync(join(root, 'slides.md'), `---
# S05 · State encryption · recommended · Day 1
src: ./pages/S05-state-encryption/index.md
hide: false
---
`)
    writeFileSync(join(root, 'slides-3day.md'), `---
# S05 · State encryption · core · Day 1
src: ./pages/S05-state-encryption/index.md
hide: false
---
---
# S18 · Integration · optional · Day 2
src: ./pages/S18-integration-cost/index.md
hide: false
---
`)
    assert.throws(
      () => validateDeckTierTruth(workshopSections, { repoRoot: root }),
      /tier drift: S05 is 'recommended' in slides\.md but 'core' in slides-3day\.md/,
    )

    writeFileSync(join(root, 'slides.md'), `---
# S05 · State encryption · core · Day 1
src: ./pages/S05-state-encryption/index.md
hide: false
---
`)
    assert.throws(
      () => validateDeckTierTruth(workshopSections, { repoRoot: root }),
      /hide invariant: S18 is 'optional' but hide='false' in slides-3day\.md/,
    )
  })

  it('renders a generated deck header marker', () => {
    const markdown = renderDeck([section('S00')], {
      title: 'Day 1',
      description: 'Author foundations',
      deck: 'day',
    })
    assert.match(markdown, /Generated by scripts\/generate-decks\.mjs/)
    assert.match(markdown, /# S00 · Topic S00 · core · Day 1/)
  })

  it('validates the live manifest against shipped section sources', () => {
    const root = resolve(import.meta.dirname, '..')
    assert.doesNotThrow(() => validateManifest(workshopSections, { repoRoot: root }))
  })

  it('validates runbook timing tables against the manifest', () => {
    const root = resolve(import.meta.dirname, '..')
    const runbook = readFileSync(join(root, 'docs/facilitator-runbook.md'), 'utf8')
    assert.doesNotThrow(() => validateRunbookTimings(workshopSections, runbook))
  })
})

describe('deck CI contract', () => {
  it('wires deck generation checks into CI', () => {
    const workflow = readFileSync(
      join(import.meta.dirname, '..', '.github', 'workflows', 'ci.yml'),
      'utf8',
    )
    for (const command of [
      'pnpm run decks:check',
      'pnpm run test:deck',
      'pnpm run build:day1',
      'pnpm run build:day2',
      'pnpm run build:day3',
    ]) {
      assert.match(workflow, new RegExp(command.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
    }
  })
})
